on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
name: deploy-traefik-to-kube
jobs:
  deploy:
    name: deploy traefik to kube
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - name: create ns traefik to kube paris
      uses: steebchen/kubectl@v2.0.0
      with:
        config: ${{ secrets.KUBE_PAR_KUBECONFIG_BASE64 }}
        command: apply -f tools/traefikns.yaml
        
    - name: create ns traefik to cluster amsterdam
      uses: steebchen/kubectl@v2.0.0
      with:
        config: ${{ secrets.KUBE_AMS_KUBECONFIG_BASE64 }}
        command: apply -f tools/traefikns.yaml
        
    - name: deploy traefik via helm to kube paris
      uses: 'deliverybot/helm@v1'
      with:
        helm: helm3
        repository: 'https://helm.traefik.io/traefik'
        release: traefik
        namespace: 'traefik'
        chart: 'traefik'
        value-files: tools/traefikvalues.yaml
      env:
        KUBECONFIG_FILE: '${{ secrets.KUBE_PAR_KUBECONFIG }}'
        
    - name: deploy traefik via helm to kube amsterdam
      uses: 'deliverybot/helm@v1'
      with:
        helm: helm3
        repository: 'https://helm.traefik.io/traefik'
        release: traefik
        namespace: 'traefik'
        chart: 'traefik'
        value-files: tools/traefikvalues.yaml
      env:
        KUBECONFIG_FILE: '${{ secrets.KUBE_AMS_KUBECONFIG }}'    
        